# config.example.yaml
server:
  port: 8090
  mode: debug # debug, release, test

database:
  host: 127.0.0.1
  port: 25432
  user: postgres.lzserver
  password: "<POSTGRES_PASSWORD>"
  dbname: postgres
  sslmode: disable

redis:
  host: 127.0.0.1
  port: 26379
  password: "<REDIS_PASSWORD>"
  db: 1

jwt:
  secret: "<JWT_SECRET>"
  expire_hour: 168 # 7 days
