# config.example.yaml
server:
  port: 8090
  mode: debug # debug, release, test

database:
  host: 127.0.0.1
  port: 55432
  user: postgres.lzserver
  password: 4uIyTQwkLOcmco7VbqDtKVaAZxOheeUZ
  dbname: postgres
  sslmode: disable

redis:
  host: 127.0.0.1
  port: 16379
  password: "4f6W2YyW9dS8vC0x"
  db: 1

jwt:
  secret: 0722b0cd7ebc3187078afe162d1e22cd6a21ea41a8cf3d60fc16b12f2a9b0c71
  expire_hour: 168 # 7 days
